export const fields = {
  theme: "E6",
  unit: "S7",
  department: "T7",
  date: "U7",
  suggestedBy: "E11",
  implementedBy: "E12",
  problem: "B15",
  whereFound: "J15",
  whenFound: "J18",
  countermeasure: "L15",
  whereImplement: "T15",
  whenImplement: "T18",
  photographBefore: "B21",
  photographAfter: "L21",
  afterKaizen: "B31",
  tangibleBenefit: "L31",
  intangibleBenefit: "P31",
  whereImplemented: "T31",
  whenImplemented: "T34",
  issueDate: "R51",
} as const;
